[project]
name = "agencia-fastapi-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[full]>=0.115.6",
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "src/tests"
